### ISSUE TITLE
is this package dead?

### ISSUE THREAD

**Issue by jantimon** [react-grid-layout/react-grid-layout#1404]
most issues are closed by the stale bot 

could you please add a note to the readme that this package is no longer maintained and bugs won't be fixed anymore?

**Comment by JamesRamm** [comment]
We are certainly feeling the frustration of the lack of maintainers. From looking at the project insights I am guessing that only @STRML has commit rights, so if they are not responsive it will be difficult to push through any PR's or have any meaningful discussion on issues.
We at siemens will probably go down the route of forking it. If there is interest, which I hope so since this package is seemingly used in production apps with a large user base (grafana, kibana, AWS cloud watch), it could be good to setup a github 'organization' to hold the project with a few invested users as maintainers.

It would be good if we could get some input from people using this in production? I will try to hunt down and reach out to a few.

**Comment by JamesRamm** [comment]
#573

**Comment by STRML** [comment]
Hey James and Jan. I haven't been able to put the kind of time into this project that it deserves due to other priorities including a new baby -- very time-consuming!

There are already three existing maintainers of this project but I assume they have also had other priorities.

For this reason I have created the [react-grid-layout organization](https://github.com/react-grid-layout) and moved this project and its dependencies to the org.

@JamesRamm, we have gotten in contact via email, let's chat briefly about getting you added to the org.

**Comment by jantimon** [comment]
Cool thanks to both of you so much for keeping this awesome project alive!! - I guess having the main developer on board is the most important part :)

I can fully understand that you moved on to new challenges.. maybe you can support the project just a little bit from time to time to transfer your knowledge to the new maintainers

**Comment by JamesRamm** [comment]
@STRML, thanks for the quick response into getting this into an org. It would be good to have someone from e.g. grafana and/or other 'big' users as a maintainer, perhaps @torkelo ?

**Comment by torkelo** [comment]
yes, that be great

**Comment by STRML** [comment]
Great, added you @torkelo.

**Comment by CareyToboo** [comment]
I am very happy that the RGL project has regained its vitality  ：）
It is indeed a great project and hope it will become more popular ～
