### ISSUE TITLE
Pass card data on the onDrop property

### ISSUE THREAD

**Issue by FernandoGOT** [react-grid-layout/react-grid-layout#1405]
I'm using the onDrop property to drag a card from outside the grid to inside, the problem is that I don't know which card I'm dragging, is there a way to pass an object or just the `i/key` property to inside the grid with the card?

**Comment by JamesRamm** [comment]
Hi
We have exactly this use case and implemented it using the drag handlers.
On the card we are dragging, we set the drag data:

```
onDragStart = e => {
   e.dataTransfer.setData('dragData', { ...some data... });
}
```
in the data we have our own internal reference to the card being dragged (e.g., we call it `widgetId`)

in react-grid-layout, we provide an `onDrop` handler to the grid and extract our data, merging it with the data from react-grid-layout:
```
const onDrop = (_, item, e) => {
   // item is the data from rgl, which contains the position, height, width etc...

   // get our custom data
   const data = JSON.parse(e.dataTransfer.getData('dragData'));
   
   // Now, we merge the data and add it to our own state. 'actions' has the handlers for modifying state - could be redux, mobx, in our case it is homegrown based on streams
   actions.addItem({ ...item, ...data });
}
```

So, you must maintain the layout data yourself so that you can enrich it with your custom data. Then when you create the grid, you can pass your layout data to the grid and create the children yourself with your own custom data:

```
<Grid layout={layout} {...rest}>
   {layout.map(item => <MyWidget key={item.i} {...item} />
</Grid>
```

RGL will just ignore any extra properties in the layout array, so you can add what you like here

**Comment by JamesRamm** [comment]
@FernandoGOT does that solve your issue?

**Comment by FernandoGOT** [comment]
@JamesRamm Sorry I'm quite busy these past days, I'm going to test this and come to give a feedback. Thanks for the help XD
