### ISSUE TITLE
Click Event doesn't fire in mobile view

### ISSUE THREAD

**Issue by manoj131990** [react-grid-layout/react-grid-layout#1410]
Hi Team,

I was checking the demo examples given in main website of react-grid-layout. In dynamic add/remove widget example (https://react-grid-layout.github.io/react-grid-layout/examples/6-dynamic-add-remove.html) click event for remove widget doesn't work for mobile devices.

![image](https://user-images.githubusercontent.com/53086611/109662406-05a36200-7b91-11eb-93e9-33b68260c1d1.png)

**Comment by uriee** [comment]
Hello All,
I couldn't handle events on child components of the ResponsiveReactGridLayout component including onMouseDown, onClick &  onDragStart.

**Comment by JamesRamm** [comment]
@uriee, there are no onMouseDown, onClick & onDragStart events for mobile in general, since there is no mouse. Touch events are for mobile. Touch events are implemented (as shown in the gif), but I am not sure that they are exposed. What is it that you are trying to do?

@manoj131990 
With chrome in 'mobile' mode I was able to remove and add widgets. Note that it would not fire a 'click' event, but a touch event. It does appear quite specific over where to press - I had to aim right in the corner - and this can perhaps be improved on mobile.

![mobile_support](https://user-images.githubusercontent.com/2784823/109769611-be51bb80-7bfa-11eb-8c6e-7f403c7c2147.gif)

**Comment by manoj131990** [comment]
@JamesRamm Yes some improvement will surely help so that User Graphical Interface would improve and also be efficient if I have multiple buttons other than close button.

**Comment by uriee** [comment]
Hello James.
Thank you for the swift response.
I Still Have the Problem.
I have a big button on each grid element.
While on mobile I can't get any event to trigger when I touch this button so I can't stop the grid element from dragging.

`  rxClick= async (e) => {
    e.stopPropagation()
    e.preventDefault();
    this.setState({ 'rx' : e.currentTarget.textContent})
  } `

`          <ResponsiveReactGridLayout
            className="layout"
            cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
            rowHeight={30}
            layouts={this.state.layouts}
            onLayoutChange={(layout, layouts) => this.onLayoutChange(layout, layouts)}
          >
            {this.state.rxs.map((x) => (
              
            <Plate key={x.id} data-grid={x.layout} >

                    <Button key={x.id+"bt"} 
                       onTouchEnd={ e => this.rxClick(e)}
                       onTouchMove={ e => this.rxClick(e)}
                       onTouchStart={ e => this.rxClick(e)}
                       onMouseDown={ e => this.rxClick(e)}
                       onClick={ e => this.rxClick(e)}
                       onDragStart={e => this.rxClick(e)}
                    >{x.name} </Button>

            
            </Plate>
            ))}
          </ResponsiveReactGridLayout>`

Thanks.

**Comment by JamesRamm** [comment]
@uriee 
I suspect the problem is in your application code, rather than RGL. Please check out this minimal example:
https://codesandbox.io/s/objective-dijkstra-7btrs

Both onClick and onTouchStart are firing as normal in this example
