### ISSUE TITLE
Grid layout not updating when changing children layout properties (`data-grid`).

### ISSUE THREAD

**Issue by linuspahl** [react-grid-layout/react-grid-layout#1563]
Creating a grid layout by defining the `data-grid` property for each children instead of providing a `layout` for the grid works well in general.

There seems to be just one disadvantage, when you change the `data-grid` prop of a child the layout is not updating.
It looks like the `childrenEqual` function in `utils` is being used to determine if the layout should be updated, but it is only comparing the keys. https://github.com/react-grid-layout/react-grid-layout/blob/master/lib/utils.js#L160

I am not sure if this behaviour is intended? There is this sentence in the readme:
```
When initializing a grid, build a layout array (as in the first example above), or attach this object as the data-grid property to each of your child elements (as in the second example).
```
which leads me to suspect the `data-grid` prop can only be used to initialize the layout.

Here is a code sandbox which demonstrates the behaviour: https://codesandbox.io/s/tender-burnell-nmh0m?file=/src/ShowcaseLayout.js

**Comment by naethiel** [comment]
Hello, I stumbled upon the same thing. I opened a ticket the other day about it: https://github.com/react-grid-layout/react-grid-layout/issues/1561 so this seems like a duplicate.

I arrived to pretty much the same conclusion, and also wonder if this is intentional (in which case it would be cool to note this in the docs) or a bug (in which case I already started digging to find a fix on my side but I'm waiting for confirmation that this is uninteded before submitting a PR)

**Comment by STRML** [comment]
Hi. This is deliberate as synchronizing it with every child data-grid prop
was deemed too expensive and error prone to do reliably. However I am open
to the idea of changing that if you think I’m wrong and there’s a fast way
to do it. Let me know your thoughts, thanks.

**Comment by naethiel** [comment]
Thanks @STRML for the answer. From what I tried, the only fash-ish way of doing it is to check for changes in `data-grid` on children iin `childrenEqual()` (which is costly but probably bearable) and then rebuild layout if they are different. Which means loosing internal changes made to the layout stored in state on all grid elements. This does not feel 100% stupid: if the parent is redefining layout through `data-grid` values, it makes sense to just rebuild the state from those values, because that's what would happen if we were using `props.layout`. I can open a PR to support the discussion if you'd like.

If we want to only update layout for the grid items which had their `data-grid` values changed, this is indeed way more costly.

**Comment by linuspahl** [comment]
Thanks for the quick answer @STRML and thanks for having a look @naethiel.

I am fine with using the `layout` prop instead, now where I know that using the `data-grid` prop is currently not a suitable solution for my use case. Since I also expect checking for `data-grid` value changes to be pretty costly, I will just create a small PR in the next days to make the current behaviour a little bit more clear in the docs.

@naethiel I will close this issue, let's use your issue (https://github.com/react-grid-layout/react-grid-layout/issues/1561) if you want to continue the discussion.
