### ISSUE TITLE
innerRef should not `React.Ref<"div">` but `React.Ref<HTMLDivElement>`

### ISSUE THREAD

**Issue by djmisterjon** [react-grid-layout/react-grid-layout#1648]
innerRef should not `React.Ref<"div">` but `React.Ref<HTMLDivElement>`
What is string "div" !!! the inner ref return a `React.Ref<HTMLDivElement>` and not a string 'div' !

**Comment by kangaechigai** [comment]
[`Ref<"div">`](https://github.com/react-grid-layout/react-grid-layout/blob/1.3.1/lib/ReactGridLayoutPropTypes.js#L94) in this case is actually [a Flow type](https://github.com/facebook/flow/blob/v0.158/lib/react.js#L213-L216) that roughly translates to the normal `React.Ref<HTMLDivElement>`. It's still not quite the right type to use here, I think, because [Flow's `React$Ref` type is apparently meant to be write-only](https://github.com/facebook/flow/issues/8671#issuecomment-862634865), not for use cases where we actually need to _read_ the `.current` value.

**Comment by STRML** [comment]
Thanks, I've updated the README to reflect this.

**Comment by STRML** [comment]
I'm going to close this as the Flow type is correct and the TypeScript type is being updated in the linked issue above thanks to @kangaechigai .
