### ISSUE TITLE
How to set variable height to child

### ISSUE THREAD

**Issue by asopromadze** [react-grid-layout/react-grid-layout#1661]
- How to set dynamic height to layout "h" key  based on child height
- [codesandbox example](https://codesandbox.io/s/optimistic-poitras-ro86q?file=/src/App.js)

**Comment by oleyva93** [comment]
I have the same problem!

**Comment by topolanekmartin** [comment]
+1

**Comment by galaxynova1999** [comment]
+1

**Comment by Gu7z** [comment]
@STRML can you help us here?

**Comment by STRML** [comment]
This feature doesn't exist as part of the lib, you'd have to measure some inner div after mount then set the item's `h` based on that item.

**Comment by STRML** [comment]
Sorry, I don't provide general programming support, that's what Discussions or Stack Overflow is for.

**Comment by Gu7z** [comment]
> measure some inner div after mount

I was thinking about that and made a [codeSandox](https://codesandbox.io/embed/react-grid-layout-dynamic-heigh-forked-mp8hlg?fontsize=14&hidenavigation=1&theme=dark) for future views. 

The ideia is set `rowHeight` to `1` and make the each item `h` be the `element.clientHeight`.

This way you can achieve dynamic height basically using `px` instead of gridUnits.
